- name: Send request to API (list public zones)
  uri:
    url: "{{ AUTH_URL_DNS }}/v2/zones?type=public"
    method: GET
    return_content: yes
    validate_certs: yes
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: zonelist_public
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: zonelist_public.status == 200
  changed_when: false
  when: zone_name is defined

- name: Send request to API (list private zones)
  uri:
    url: "{{ AUTH_URL_DNS }}/v2/zones?type=private"
    method: GET
    return_content: yes
    validate_certs: yes
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: zonelist_private
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: zonelist_private.status == 200
  changed_when: false
  when: zone_name is defined

- name: Set fact zonelist_result
  set_fact:
    zonelist_result: "{{ zonelist_public.json.zones }} + {{ zonelist_private.json.zones }}"
  when: zone_name is defined

- name: Set fact zone_id for dns if zone_name is defined
  vars:
    zonenamedot: "{{ zone_name }}."
  set_fact:
    zone_id: "{{ zonelist_result|json_query(\"[?name=='\" + zonenamedot + \"'].id|[0]\") }}"
  when: zone_name is defined
