- name: Send request to API (list ptr)
  uri:
    url: "{{ AUTH_URL_DNS }}/v2/reverse/floatingips"
    method: GET
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    status_code: 200,201,202,203,400
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: ptrrecord
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: ptrrecord.status == 200 or ptrrecord.status == 201 or ptrrecord.status == 202 or ptrrecord.status == 203 or ptrrecord.status == 400
  changed_when: false

- debug:
    msg: "{{ ptrrecord }}"
