- name: Lookup zone_id
  include: lookup.yml

- name: Send request to API (show zone)
  uri:
    url: "{{ AUTH_URL_DNS }}/v2/zones/{{ zone_id }}"
    method: GET
    return_content: yes
    validate_certs: yes
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: zone
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: zone.status == 200
  changed_when: false
  when: zone_id is defined

- debug: var=zone.json
  when: zone is defined
