---
- name: Call dig to catch zone information
  shell: dig +noall +answer {{ zone_name }} @{{ dns_server }} axfr | grep -E '(\s+)(A|AAAA|CNAME|MX)'
  register: zone_data

- name: Create dns.ini file
  template:
    src: dns.ini.j2
    dest: ./dns.ini
    force: yes
    backup: yes
  when: config == "ini"

- name: Create dns.yml file
  template:
    src: dns.yml.j2
    dest: ./dns.yml
    force: yes
    backup: yes
  when: config == "yml"

- name: Create dns.json file
  template:
    src: dns.json.j2
    dest: ./dns.json
    force: yes
    backup: yes
  when: config == "json"
