- name: Send request to API (create zonerecords)
  vars:
    zonerecord_part: "{{ item.split(';') }}"
  uri:
    url: "{{ AUTH_URL_DNS }}/v2/zones/{{ zone_id }}/recordsets"
    method: POST
    body_format: raw
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    status_code: 200,201,202,203,400
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'zonerecord_create.json.j2')|to_json }}"
  register: zonerecord
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: zonerecord.status == 200 or zonerecord.status == 201 or zonerecord.status == 202 or zonerecord.status == 203 or zonerecord.status == 400
  changed_when: false
  with_items:
    - "{{ zone_records }}"
